# Generated by Django 4.2.2 on 2023-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coach_no', models.IntegerField()),
                ('seat_no', models.IntegerField()),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.TextField(max_length=100)),
                ('train_name', models.TextField(max_length=100)),
                ('arrival_time', models.TimeField()),
            ],
            options={
                'db_table': 'station_schedule',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station1', models.TextField()),
                ('station2', models.TextField()),
                ('station3', models.TextField()),
                ('station4', models.TextField()),
                ('station5', models.TextField()),
                ('station6', models.TextField()),
                ('station7', models.TextField()),
                ('station8', models.TextField()),
                ('station9', models.TextField()),
                ('station10', models.TextField()),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('station_name', 'arrival_time'), name='unique_station_schedule'),
        ),
    ]
